/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class unicorn_voice_spectrogram_Spectrogram */

#ifndef _Included_unicorn_voice_spectrogram_Spectrogram
#define _Included_unicorn_voice_spectrogram_Spectrogram
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     unicorn_voice_spectrogram_Spectrogram
 * Method:    read
 * Signature: ([BIFF)V
 */
JNIEXPORT void JNICALL Java_unicorn_voice_spectrogram_Spectrogram_read
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
